/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct QUEUE {
	int num;
	int pid;
	int result;
};
typedef struct QUEUE QUEUE;

#define RPC_PROG 0x20000021
#define RPC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_NUMBER 1
extern  struct QUEUE * get_number_1(void *, CLIENT *);
extern  struct QUEUE * get_number_1_svc(void *, struct svc_req *);
#define WAIT_RESULT 2
extern  struct QUEUE * wait_result_1(struct QUEUE *, CLIENT *);
extern  struct QUEUE * wait_result_1_svc(struct QUEUE *, struct svc_req *);
extern int rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_NUMBER 1
extern  struct QUEUE * get_number_1();
extern  struct QUEUE * get_number_1_svc();
#define WAIT_RESULT 2
extern  struct QUEUE * wait_result_1();
extern  struct QUEUE * wait_result_1_svc();
extern int rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_QUEUE (XDR *, QUEUE*);

#else /* K&R C */
extern bool_t xdr_QUEUE ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
