/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct QUEUE *
get_number_1(void *argp, CLIENT *clnt)
{
	static struct QUEUE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_NUMBER,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_QUEUE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct QUEUE *
wait_result_1(struct QUEUE *argp, CLIENT *clnt)
{
	static struct QUEUE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, WAIT_RESULT,
		(xdrproc_t) xdr_QUEUE, (caddr_t) argp,
		(xdrproc_t) xdr_QUEUE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
