/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"


void
rpc_prog_1(char *host)
{
	CLIENT *clnt;
	struct QUEUE  *result_1;
	struct QUEUE  get_number_1_arg;
	struct QUEUE  *result_2;
	struct QUEUE  wait_result_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_PROG, RPC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Start get_number_1\n");
	result_1 = get_number_1(&get_number_1_arg, clnt);
	if (result_1 == (struct QUEUE *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("get_number_1 result = %d\n", result_1->pid);
	wait_result_1_arg.num = result_1->num;
	wait_result_1_arg.pid = result_1->pid;
	result_2 = wait_result_1(&wait_result_1_arg, clnt);
	if (result_2 == (struct QUEUE *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("wait_result_1 result = %c\n", result_2->result);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_prog_1 (host);
exit (0);
}
