/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include <unistd.h>

#define SIZE 30

int choosing[SIZE] = { 0 };
int number[SIZE] = { 0 };
int sym = 'a';
int num = 0;

struct QUEUE *get_number_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct QUEUE result;
	int i = num++;
	result.pid = i;
	choosing[i] = 1;
	int max = 0;
	for (int j = 0; j < SIZE; j++)
		if (number[j] > max)
			max = number[j];
	number[i] = max + 1;
	result.num = number[i];
	choosing[i] = 0;
	return &result;
}

struct QUEUE *wait_result_1_svc(struct QUEUE *argp, struct svc_req *rqstp)
{
	static struct QUEUE result;
	int i = argp->pid;
	for (int j = 0; j < 30; j++)
	{
		while (choosing[j]);
		while ((number[j] > 0) && (number[j] < number[i] || (number[j] == number[i] && j < i)));
	}

	result.result = sym++;
	sleep(6);
	
	number[i] = 0;	
	
	return &result;
}
